### ISSUE TITLE
Capture focus for non 'withBackdrop' overlays not working

### ISSUE THREAD

**Issue by sjmoreno** [PolymerElements/iron-overlay-behavior#107] opened 2016-02-16 23:36 UTC
After installing 1.3.0, focus on iron-inputs in 'paper-dialog' stopped working. I cannot focus on any input after clicking anywhere else on the dialog or outside the dialog. *Seems* like this might be the breaking change https://github.com/PolymerElements/iron-overlay-behavior/commit/a72f902659e08868baadec909608dce50acb8b72 added a new listener for 'focus' but it is only handling it when having a dialog 'withBackdrop'. When I get rid of the listener the focus starts working just fine.

**Comment by valdrinkoshi** [comment] 2016-02-17 01:13
I could not reproduce it jsbin.com/nalulo/1/edit, closing.
Can you provide a jsbin exposing the issue? I'll reopen this if there is an issue

**Closed by valdrinkoshi** 2016-02-17 01:13 UTC

**Comment by valdrinkoshi** [comment] 2016-02-17 01:14
You should maybe update also `paper-dialog-behavior` and `paper-dialog` to their latest version :)
