### ISSUE TITLE
iron-overlay-backdrop conflict with app-header-layout

### ISSUE THREAD

**Issue by Gaubee** [PolymerElements/iron-overlay-behavior#215] opened 2016-09-12 13:36 UTC
### Description
`<iron-overlay-backdrop>` will append to `<body>`.
When I use `<app-header-layout>` , `<iron-overlay-backdrop>` will keep to top. because the `<app-header-layout>`  will be set `z-index` as `0` . so will be aways under `<iron-overlay-backdrop>` , and lost control of the pop-up box.

Similar code would happen if developers use the z-index attribute to control layout.

### Expected outcome

`<iron-overlay-backdrop>` shoud be under pop-up box

### Actual outcome

`<iron-overlay-backdrop>` always at the top

### Live Demo

https://jsbin.com/suticenuwu/1/edit?html,output

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by valdrinkoshi** [comment] 2016-09-13 01:54
Hi @Gaubee, looks like a duplicate of https://github.com/PolymerElements/iron-overlay-behavior/issues/208#issuecomment-234321807
Unfortunately solutions like adding the backdrop as child of the overlay (see [this PR](https://github.com/PolymerElements/iron-overlay-behavior/pull/180)) would be a breaking change :/

**Comment by valdrinkoshi** [comment] 2016-09-13 01:57
For the time being, the best is to declare `paper-dialog` as a sibling of `app-drawer-layout`, e.g.  https://jsbin.com/likela/2/edit?html,output

Closing as this is a duplicate

**Closed by valdrinkoshi** 2016-09-13 01:57 UTC

**Comment by ergo** [comment] 2016-12-27 18:44
Is there any other solution to this?

With lazy-loaded elements, and template bindings it seems that advice to put everything outside of drawer is very problematic.

**Comment by ergo** [comment] 2017-08-21 21:20
@valdrinkoshi do you know of any other workarounds? It seems that there is no way to use latest `app-layout` with `paper-dialog`, is there a way to force context correctly? I don't think there is a good way to put the dialog on same level as `app-layout` since real applications using `iron-lazy-pages` or some other router will inject their view components somewhere deeper in the hierarchy.

**Comment by ergo** [comment] 2017-08-21 21:29
@valdrinkoshi in my scenario application looks like this:

            <app-drawer-layout>
                <app-header condenses reveals effects="waterfall">
                    <app-toolbar>....</app-toolbar>
                </app-header>
                <app-drawer slot="drawer">....</app-drawer>
                <uirouter-uiview>...this injects view elements that will use dialogs...</uirouter-uiview>
            </app-drawer-layout>

**Comment by sunc9oa** [comment] 2017-08-31 08:58
@ergo Hi, you can listening `iron-overlay-opened` and `iron-overlay-closed` event, this two event come from `Polymer.IronOverlayBehavior`, when `iron-overlay-opened` event fired, set `drawer.style.zIndex` to 0, when `iron-overlay-closed` event event fired, set` drawer.style.zIndex` back to 1.

If your content under the backdrop, here have a patch [](https://github.com/PolymerElements/paper-dialog/issues/7#issuecomment-118497040) to solve the problem.
