### ISSUE TITLE
Multiple modal dialogs result in broken functionality

### ISSUE THREAD

**Issue by bendavis78** [PolymerElements/iron-overlay-behavior#58] opened 2015-11-25 20:14 UTC
Looking through `iron-overlay-manager.html`, it looks like multiple overlays with backdrops are expected to work.  It seems to be broken, though. 

http://jsbin.com/taxoli/47/edit?html,output

In this example, the second overlay should have a backdrop, but the backdrop is still under the first. Looking at the source, it seems as if the backdrop is meant to move under the top-most dialog.

Other problems can occur when nesting overlays with backdrops. The backdrop is appended to the body, so it can't exist in the Z-space between the nested overlay element and its ancestor.

**Comment by valdrinkoshi** [comment] 2016-01-15 18:15
Hi @bendavis78, in your demo you forgot to close `paper-dialog#main` tag, and that was causing the secondary to close both of the dialogs
http://jsbin.com/vovabud/1/edit?html,console,output
About the backdrop `z-index`, this is by design to have it low enough to display all overlays that are `opened` and `with-backdrop`. 
@cdata, we could either add a property `always-on-top` (already asked in #3), or change the functionality. WDYT?

**Comment by motss** [comment] 2016-01-28 09:17
:+1: A must-have feature for dialog. Meantime this might help but proper implementation is definitely needed in `paper-dialog`.

http://jsbin.com/masudugixe/edit?html,console,output

**Comment by valdrinkoshi** [comment] 2016-01-29 00:09
@motss I didn't understand your jsbin, it doesn't have any overlay.
Closing this as duplicate of #3

**Closed by valdrinkoshi** 2016-01-29 00:09 UTC
Labels: enhancement
