### ISSUE TITLE
iron-overlay-behavior does not properly scope styles

### ISSUE THREAD

**Issue by zikes** [PolymerElements/iron-overlay-behavior#23] opened 2015-07-03 07:16 UTC
http://stackoverflow.com/questions/31199823/iron-overlay-behavior-styling-not-taking-effect

I have implemented the above component at http://polymer.zikes.me/bower_components/my-overlay/. You will see that changing the custom CSS variables do not have an effect on the backdrop.

I believe this is partly because the backdrop is created but not added to the parent component's scope.  Adding the line `this.scopeSubtree(this._backdrop);` to the `registered` function of `iron-overlay-behavior.html` should resolve that, however the component's `<style>` and contents are still not copied into the parent document to apply those styles, and I do not know how to resolve that.

**Comment by miztroh** [comment] 2015-09-19 04:31
@cdata: I'm seeing this too.  After watching @ebidel's talk at the Polymer Summit, I built one element as an app shell.  Then I built all its functionality into separate custom elements.  In this way, the app shell loads more or less instantly.  The custom elements its contains are loaded from a separate import.  However, doing it this way is causing issues for me in Chrome (but not polyfilled browsers).  Below is an example involving the iron-dropdown overlay in paper-menu-button, but paper-dialog is affected as well.

Included are screenshots of how the menu is rendered in Chrome vs other browsers, as well as the dev tools window.  Dev tools shows that the background-color style rule is broken.  I don't get the elevation shadow either.  However, the exact same code works on IE, Edge, and Firefox.

I hope this can be resolved soon.  It's quite the show stopper.

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/2515209/9964336/56a99238-5df5-11e5-9dcf-7dfb2d1bca1a.png)

Others:
![others](https://cloud.githubusercontent.com/assets/2515209/9964342/5b865444-5df5-11e5-83aa-cd086c335349.jpg)

![devtools](https://cloud.githubusercontent.com/assets/2515209/9964345/5e2881e0-5df5-11e5-8522-b2733d13a0f2.png)

**Comment by cdata** [comment] 2015-10-20 00:29
Hey guys, I think this is a z-index issue, not a style scoping issue. This is a known deficiency of `IronOverlayBehavior`, and we are working on an alternative approach to resolve this. However, the alternative approach will manifest as a new element, so I am going to close this issue for now. Please re-open if you think I have mis-interpreted anything!

**Comment by miztroh** [comment] 2015-10-20 02:47
@cdata Take a look at the screenshot I posted, specifically at the red rectangle I added.  It highlights a broken CSS rule.  Are you sure that this is due to a z-index issue?

**Comment by zikes** [comment] 2015-10-20 03:29
I'm pretty sure it's a shady DOM issue, since manually calling `scopeSubtree` fixes it.

**Comment by miztroh** [comment] 2015-10-20 13:26
@zikes Will you reopen?

**Comment by zikes** [comment] 2015-10-20 18:05
@miztroh I'm not seeing an option to reopen, I don't think I have the necessary permissions.

**Comment by miztroh** [comment] 2015-10-20 18:13
@cdata Will you reopen and take another look?

**Comment by valdrinkoshi** [comment] 2016-01-08 16:03
@miztroh @zikes `iron-overlay-backdrop` will be added to `body`, so you have to apply the styles like this:
```html
    <body>

      <style is="custom-style">
        iron-overlay-backdrop {
          --iron-overlay-backdrop-opacity: 0.9;
          --iron-overlay-backdrop-background-color: #222;
        }
      </style>
    
      <my-overlay></my-overlay>
 
    </body>

**Comment by miztroh** [comment] 2016-01-08 16:13
@valdrinkoshi This issue for me (see my post above) was not for some custom use of iron-overlay-backdrop.  I was having issues with things like paper-dropdown-menu and paper-dialog not having correct styles in certain cases.

**Comment by valdrinkoshi** [comment] 2016-01-08 18:17
@miztroh could you provide an jsbin?
I've tried with this one and I cannot reproduce the issue
http://jsbin.com/lepubi/1/edit?html,output
Here the code for `my-overlay` http://jsbin.com/pivowey/1/edit?html,output

**Comment by valdrinkoshi** [comment] 2016-01-08 18:21
`iron-overlay-backdrop` is be a single instance shared across overlays. It is added to `body`, so the style must be done at that level, not within a custom-element

**Comment by miztroh** [comment] 2016-01-08 20:00
It's a little too complicated to demonstrate with JSbin, so I created a GitHub repo demonstrating the issue.  It uses paper-menu-button for illustration, but the problem exists with other overlay uses as well (paper-dialog, etc.).

Repo: https://github.com/miztroh/bug-shell

Async test case: Works in polyfill browsers; broken in Chrome
https://miztroh.github.io/bug-shell/async.html

Sync test case: Works in all browsers
https://miztroh.github.io/bug-shell/sync.html

**Comment by valdrinkoshi** [comment] 2016-01-08 20:24
Cool, thanks for that! :) 
verified locally, reopening this.

**Comment by miztroh** [comment] 2016-01-08 20:46
No problem.  Hope we can get this worked out.  I really want to start rolling out my app shell as a replacement for my synchronous (slower) all-in-one app element.

**Comment by valdrinkoshi** [comment] 2016-01-11 14:53
@miztroh, I've played with your repo and simplified the example in here https://github.com/valdrinkoshi/bug-shell
The problem is not caused by `iron-overlay-behavior` (as you'll see in my example I have only custom elements), but by the usage of `async`.
@cdata where should this issue be moved?

**Comment by notwaldorf** [comment] 2016-01-27 23:27
Closing, as this is a core problem (Polymer/polymer#2481), and will be fixed when that is fixed.

**Closed by notwaldorf** 2016-01-27 23:27 UTC
