### ISSUE TITLE
__[first|last]FocusableNode should not be stored

### ISSUE THREAD

**Issue by mhahmadi** [PolymerElements/iron-overlay-behavior#197] opened 2016-06-21 21:04 UTC
An overlay dialog element's children might change dynamically. For example, the dialog could have an 'OK' button that is initially disabled, but gets enabled once some selection is made in the dialog.

### Expected outcome

Once the 'OK' button becomes enabled it should get focus.

### Actual outcome

the 'OK' button won't get focus b/c focusable nodes are cached when the dialog is initially displayed.

Possible solution: Either they shouldn't be cached, or they should be @protected properties so they can be overridden.

**Comment by valdrinkoshi** [comment] 2016-06-21 23:01
Hi @mhahmadi, this looks like a duplicate of https://github.com/PolymerElements/iron-overlay-behavior/issues/184. 
[This comment](https://github.com/PolymerElements/iron-overlay-behavior/issues/184#issuecomment-220494270) should be helpful :)
Closing this as duplicate

**Closed by valdrinkoshi** 2016-06-21 23:01 UTC

**Comment by mhahmadi** [comment] 2016-06-21 23:30
Thank you for the prompt response.
