### ISSUE TITLE
Styling backdrop is impossible/unsatisfyingly difficult

### ISSUE THREAD

**Issue by AndreasGalster** [PolymerElements/iron-overlay-behavior#166] opened 2016-05-01 03:52 UTC
When wanting to style a paper-dialog it's almost impossible to style the backdrop. Since the backdrop get's added to the body, the only way to style it is via :root. This in itself already makes it very difficult to style it differently per element.

Element 1 with paper-dialog might have a black background, element 2 might use a blue background.

Now the only way to somehow conditionally fix that would be by assigning a class perhaps, which doesn't seem to work though. If you do :root.class {} this doesn't work. Using iron-overlay-backdrop {} works again, whereas something like iron-overlay-backdrop.blue {} doesn't work. Now if by some chance you can find a way to make the backdrop to pick up the styling up via the class there's still another issue: You could only add a class to the backdrop once it's in the body. So doing paper-dialog.toggle() and then paper-dialog.backdropElement.classList.add('blue') doesn't even work either because the timing between toggle and add is off. Ok, guess we could prepare the backdrop first and then add the class. (I have not tried this yet but I assume that would work).

I hope you see where this is going. All I wanted to do was color the backdrop and change the opacity for one paper-dialog. I've spent a few hours coming up with a solution (and still don't have one). I'd suggest an improvement here. I have no idea how to improve it though :P.

For anyone wondering, this is a temporary but definitely ugly hack to get a decent result. In the main document:

`
  <style>
    iron-overlay-backdrop.blue[opened] {
      background: #2196f3;
      opacity: 1;
      transition: opacity 1s ease;
      transition: background 0.3s ease;
    }
  </style>
`

**Comment by valdrinkoshi** [comment] 2016-05-02 18:29
Hi @AndreasGalster, the `iron-overlay-backdrop` is by design a singleton, hence is shared by all the overlays (in fact it gets generated by the `iron-overlay-manager` and appended to `document.body`).
I'd suggest to toggle a css class on the backdrop right before you open the overlay, e.g. http://jsbin.com/hecehib/5/edit?html,output
I noticed that custom properties don't work, @cdata @notwaldorf any ideas why?

**Comment by valdrinkoshi** [comment] 2016-05-24 19:12
@AndreasGalster, there are 2 ways to tackle this problem:
- move the `iron-overlay-backdrop` into the root of the opened overlay (see [backdrop-in-overlay](https://github.com/PolymerElements/iron-overlay-behavior/compare/backdrop-in-overlay) branch); this would keep the backdrop as a singleton, and would allow to style it according to the overlay that contains it (see this jsbin http://jsbin.com/zixuxe/3/edit?html,output)
- create a backdrop for each overlay with backdrop (see [backdrop-as-style](https://github.com/PolymerElements/iron-overlay-behavior/compare/backdrop-as-style) branch); this would have a separate backdrop for each overlay, and would allow to have overlapping backdrop colors when opening multiple overlays (see this jsbin http://jsbin.com/letabi/4/edit?html,output)

I would vote for the second option (multiple backdrops), and I'd also move this feature to the `paper-dialog-behavior` as it is the only overlay leveraging `with-backdrop`.

In any case, both options would introduce a breaking change (mainly for styling the backdrop), hence they can't be landed at the present moment.

**Closed** 2016-06-06 21:43 UTC
Labels: breaking-change, p1 - backlog
