### ISSUE TITLE
Overlay suffers infinite recursive cycle when calling `_applyFocus`

### ISSUE THREAD

**Issue by cdata** [PolymerElements/iron-overlay-behavior#31] opened 2015-08-11 23:11 UTC

**Comment by cdata** [comment] 2015-08-12 00:05
Relevant: https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-manager.html#L63-L76

**Comment by bflora2** [comment] 2015-08-19 14:08
I'm glad this is being looked at! I'm seeing "Maximum call stack size exceeded" exceptions from the field due to this issue. It is very easy to reproduce by repeatedly opening and closing an animated dialog in rapid fire succession. I put a check in my code to prevent that, but I still see occasional exceptions from the field when two paper-element animations happen to occur at the same time.

**Closed** 2015-08-27 21:51 UTC
