### ISSUE TITLE
focus breaks even with noAutoFocus

### ISSUE THREAD

**Issue by ahedderich** [PolymerElements/iron-overlay-behavior#139] opened 2016-03-23 14:16 UTC
I use a paper-dialog to show a paper-input for a search query. 
When there is a paper-toast triggered in the background the input loses focus when the toast hides again.
Wouldn't it make more sense to prevent the blur also if the noAutoFocus attribute is set?
Like this:
```javascript
    _applyFocus: function() {
      if (!this.noAutoFocus) {
        if (this.opened) {
          this._focusNode.focus();
        } else {
          this._focusNode.blur();
          this._focusedChild = null;
          this._manager.focusOverlay();
        }
      }
    },
```

**Comment by valdrinkoshi** [comment] 2016-03-23 15:42
Good catch, thanks for reporting! If you feel like it, feel free to open a PR with the fix :)

**Comment by valdrinkoshi** [comment] 2016-03-25 22:50
Hi @ahedderich, I did some testing and could not reproduce the issue http://jsbin.com/nuqata/3/edit?html,output
Each overlay blurs its own `_focusNode` on close, so the toast does it for its own without interfering with the `_focusNode` of the dialog.
Closing this, feel free to provide a jsbin with the example of the bug if you still face the issue, and i'll re-open it.

**Closed by valdrinkoshi** 2016-03-25 22:50 UTC
Labels: bug, p1 - backlog

**Comment by ahedderich** [comment] 2016-04-02 08:54
Hi @valdrinkoshi, sorry for the late answer. You're right. If you set the `paper-dialog` to `no-auto-focus` it works. 
It's not a big deal, but I still think it's not quite right. Since `paper-toast` is set to `no-auto-focus` by default, it shouldn't interfere with the behavior of `paper-dialog` either way.
if you use a `paper-dialog` with autofocus in any circumstance, the `applyFocus()` is triggered, again even though the `paper-toast` didn't take over the focus. 
So `this._manager.focusOverlay();` shouldn't be invoked by an element, that didn't change any focus in the first place.

**Comment by valdrinkoshi** [comment] 2016-04-04 17:45
`this._manager.focusOverlay();` basically guarantees that the top overlay executes its `_applyFocus` correctly. It is needed when we close the overlay & need to say to the newly top overlay to apply the focus. I agree this could done in a cleaner way, as the manager is already tracking the focus changes and knows when we want to add/remove an overlay.
