### ISSUE TITLE
Opening from on-tap causes immediate close.

### ISSUE THREAD

**Issue by wintersandroid** [PolymerElements/iron-overlay-behavior#14] opened 2015-06-01 23:57 UTC
Basic scenario, have an item, which within its on-tap a non-modal paper-dialog, the overlay flashes up (sometimes slow enough to see) and then closes.

Using on-click it will appear, seems the handling of on-tap causes two events.

```
  <paper-item id="master" on-tap="tapMasterItem">{{currentLabel}}</paper-item>
    <paper-dialog id="menuDialog" with-backdrop="false">
      <paper-dialog-scrollable>
        <paper-menu selected="{{currentValue}}">
          <template as="dataitem" is="dom-repeat" items="{{items}}">
            <paper-item id="{{getValue(dataitem)}}" >{{getLabel(dataitem)}}</paper-item>
          </template>
        </paper-menu>
      </paper-dialog-scrollable>
    </paper-dialog>

    tapMasterItem: function(){
      if(!this.$.menuDialog.opened){
        this.$.menuDialog.open();
      }
    },
```

**Comment by davidcv5** [comment] 2015-06-03 03:26
I'm having the same problem...

**Comment by himu62** [comment] 2015-06-06 07:25
I had the same problem, and resolved by modifying the code in 'iron-overlay-behavior.html'.

original @ lines 282-283
```js
this._toggleListener(this.opened, document, 'click', this._boundOnCaptureClick, true);
this._toggleListener(this.opened, document, 'keydown', this._boundOnCaptureKeydown, true);
```

fixed
```js
this._toggleListener(!this.opened, document, 'click', this._boundOnCaptureClick, true);
this._toggleListener(!this.opened, document, 'keydown', this._boundOnCaptureKeydown, true);
```

http://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-behavior.html#L282-283

**Comment by himu62** [comment] 2015-06-06 09:40
Sorry, my test is not enough and the code I posted is not work well.

I also tried modify the code on line 285, add the delay to the function.

```js
this._toggleListenersAsync = this.async(function() {
    this._toggleListener(this.opened, document, 'click', this._boundOnCaptureClick, true);
    this._toggleListener(this.opened, document, 'keydown', this._boundOnCaptureKeydown, true);
    this._toggleListenersAsync = null;
  }, 100);
```

It seems to be working well.

**Comment by ronnyroeller** [comment] 2015-07-23 22:36
+1

**Comment by pe4enushkin** [comment] 2015-07-29 14:12
+1

**Comment by tdesc** [comment] 2015-09-05 08:50
This bug is very critical. All mobile apps with iron-overlay-behaviour ( dialogs ) not function.

**Comment by alexandrubichis** [comment] 2015-09-11 07:25
+1

**Comment by jptrainor** [comment] 2015-09-14 23:52
+1

**Comment by valdrinkoshi** [comment] 2016-01-08 15:46
It seems the issue is already fixed http://jsbin.com/vonoge/1/edit?html,output
Closing this

**Comment by valdrinkoshi** [comment] 2016-01-08 15:47
@wintersandroid @tdesc @himu62 and others, please let me know if it is still an issue (with a code example if possible), and I'll reopen this

**Closed by valdrinkoshi** 2016-01-08 15:46 UTC
Labels: bug
